version: "3"

services:
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
    - mongo_data:/data/db

  app:
    container_name: api_container
    build: .
    ports:
      - 4000:3000
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_URL: ${SERVER_URL}
      MONGO_URI: mongodb://database_container:27017/not-today
      PRIVATE_KEY: ${PRIVATE_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}