import { GraphQLError } from "graphql";

export enum AppErrors {
  "REQUIRED_FIELD" = "REQUIRED_FIELD",
  "EMAIL_ALREADY_EXISTS" = "EMAIL_ALREADY_EXISTS",
  "INVALID_CREDENTIALS" = "INVALID_CREDENTIALS",
  "EMAIL_NOT_VERIFIED" = "EMAIL_NOT_VERIFIED",
  "USER_NOT_FOUND" = "USER_NOT_FOUND",
  "DIARY_NOT_FOUND" = "DIARY_NOT_FOUND",
  "LEVEL_NOT_FOUND" = "LEVEL_NOT_FOUND",
  "ADDICTION_NOT_FOUND" = "ADDICTION_NOT_FOUND",
  "USER_ADDICTION_NOT_FOUND" = "USER_ADDICTION_NOT_FOUND",
  "UNAUTHENTICATED" = "UNAUTHENTICATED",
  "UNAUTHORIZED" = "UNAUTHORIZED",
  "SAME_DAY_DIARY" = "SAME_DAY_DIARY",
  "INVALID_MOOD" = "INVALID_MOOD",
  "INVALID_LEVEL" = "INVALID_LEVEL",
  "ALREADY_HAVE_ADDICTION" = "ALREADY_HAVE_ADDICTION",
  "INVALID_ADDICTION" = "INVALID_ADDICTION",
  "REDIS_ERROR" = "REDIS_ERROR",
}

export class AppError extends GraphQLError {
  constructor(message: string, code: AppErrors, input?: any) {
    super(message, {
      extensions: {
        code,
        input,
      },
    });
  }
}
